name: letter-for-you

services:
  postgres:
    image: postgres:16
    container_name: letter_for_you_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: letter_for_you_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - letter_for_you_postgres_data:/var/lib/postgresql/data

volumes:
  letter_for_you_postgres_data: